### ISSUE TITLE
Add a preload="none" option.

### ISSUE THREAD

**Issue by sonnety** [audiotheme/jquery-cue#4]
Hello I've create playlist but all mp3s are auto downloading on load. How to add preload="none" option to the script or on audio tag `$media = $( "<audio />",` ?

**Comment by bradyvercher** [comment]
Hi @sonnety. That's not possible right now, but only the first file in the playlist will be preloaded. The other tracks in the playlist use the same `<audio>` element, so they won't be preloaded.

**Comment by sonnety** [comment]
Is your pro version has that features?

**Comment by bradyvercher** [comment]
No, it would need to be added as a configuration option in this library.

**Comment by sonnety** [comment]
I've simple music website and i'm using php so i create two playlist which are php foreach generated. but  first file of all playlist preloading so my site taking a huge time to load. can you provide a code ? how to fix it ? . sorry for bad english. 

`jQuery( document).ready(function( $ ) { 
$( '.playlist<?php echo $music['music_id']; ?>' ).cuePlaylist({
cuePlaylistLoop: true, 
cuePlaylistTracks: [ <?php foreach($music['musics'] as $getmusic ) { ?>  { src: 'image/<?php echo $getmusic['musics']; ?>', title: '<?php echo $getmusic['title']; ?>' }, <?php } ?> <?php } ?>], cueSkin:'custom-skin', cueSelectors: {playlist: '.playlist<?php echo $music['music_id']; ?>', track: '.track<?php echo $music['music_id']; ?>', tracklist: '.tracks<?php echo $music['music_id']; ?>'}, features: ['cuecurrentdetails','cueprevioustrack','playpause','cuenexttrack','current','duration','cueplaylist'], }) ; });`

**Comment by sonnety** [comment]
Thanks i fixed it.

**Comment by bradyvercher** [comment]
Thanks for following up, @sonnety. Can you let me know what you did in case anyone else runs into a similar issue?
